name: weightloss-habit-tracker
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=local
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      # https://github.com/docker-library/postgres/blob/22ca5c8d8e4b37bece4d38dbce1a060583b5308a/18/trixie/Dockerfile#L189
      - ./pgdata:/var/lib/postgresql

networks:
  app:
